//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.SolicitudInspeccion = new HashSet<SolicitudInspeccion>();
        }
    
        public int idcliente { get; set; }
        public string nombre { get; set; }
        public string apellidopat { get; set; }
        public string apellidomat { get; set; }
        public string direccion { get; set; }
        public string refedireccion { get; set; }
        public int telefonono { get; set; }
        public string email { get; set; }
        public Nullable<int> celular { get; set; }
    
        public virtual ICollection<SolicitudInspeccion> SolicitudInspeccion { get; set; }
    }
}
