//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_empleado
    {
        public int idempleado { get; set; }
        public int idinspeccion { get; set; }
        public Nullable<bool> responsable { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Inspeccion Inspeccion { get; set; }
    }
}
