//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Producto
    {
        public int iddetallepro { get; set; }
        public int idproducto { get; set; }
        public int idinspeccion { get; set; }
        public int cantidad { get; set; }
        public string observacion { get; set; }
        public Nullable<bool> venta { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Inspeccion Inspeccion { get; set; }
    }
}
