//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public Empleado()
        {
            this.Det_empleado = new HashSet<Det_empleado>();
        }
    
        public int idempleado { get; set; }
        public Nullable<int> dni { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
    
        public virtual ICollection<Det_empleado> Det_empleado { get; set; }
    }
}
