//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspeccion
    {
        public Inspeccion()
        {
            this.Det_empleado = new HashSet<Det_empleado>();
            this.Det_Producto = new HashSet<Det_Producto>();
        }
    
        public int idinspeccion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string observaciones { get; set; }
        public Nullable<System.DateTime> diadeinspeccion { get; set; }
        public Nullable<System.TimeSpan> horainspeccion { get; set; }
        public Nullable<int> idestado { get; set; }
        public Nullable<int> idtiposervi { get; set; }
        public Nullable<int> idsolicitud { get; set; }
    
        public virtual ICollection<Det_empleado> Det_empleado { get; set; }
        public virtual ICollection<Det_Producto> Det_Producto { get; set; }
        public virtual estado estado { get; set; }
        public virtual SolicitudInspeccion SolicitudInspeccion { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
