//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudInspeccion
    {
        public SolicitudInspeccion()
        {
            this.Inspeccion = new HashSet<Inspeccion>();
        }
    
        public int idsolicitud { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string referencias { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public Nullable<int> idcliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    }
}
