//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_rol
    {
        public tb_rol()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idRol { get; set; }
        public string descRol { get; set; }
        public bool estadoRol { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
