//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoolProy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicio
    {
        public TipoServicio()
        {
            this.Inspeccion = new HashSet<Inspeccion>();
        }
    
        public int idtiposervi { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Inspeccion> Inspeccion { get; set; }
    }
}
